---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: bluegreen-app

  labels:
    app: bluegreen-app
    color: blue

spec:
  replicas: 2

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: bluegreen-app
      color: blue

  template:
    metadata:
      labels:
        app: bluegreen-app
        color: blue

    spec:
      containers:
        - name: bluegreenapp

          image: pratiksha1402/bluegreen-app:v2

          imagePullPolicy: Always

          ports:
          - containerPort: 8080

...
