---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: bluegreenapp-green

  labels:
    app: bluegreen-app
    color: green

spec:
  replicas: 2

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: bluegreen-app
      color: green

  template:
    metadata:
      labels:
        app: bluegreen-app
        color: green

    spec:
      containers:
        - name: bluegreenapp

          image: pratiksha1402/bluegreen-app:v1

          imagePullPolicy: Always

          ports:
          - containerPort: 8080

...
